# roles/mariadb/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes
  tags: mariadb

- name: Install config file for network settings
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config }}"
  notify: restart mariadb
  tags: mariadb

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Results
  debug:
    msg: "RC: {{ root_pwd_check.rc }}\n{{ root_pwd_check.stderr }}"

- name: Set MariaDB root password for the first time
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: Set MariaDB root password for local hostnames
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: root_pwd_check.rc != 0
  tags: mariadb

- name: Set MariaDB root password for ‘external’ host name
  mysql_user:
    name: root
    host: "{{ ansible_hostname }}"
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  when: ansible_hostname != 'localhost' and root_pwd_check.rc != 0
  tags: mariadb

- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent
  tags: mariadb

- name: Remove anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags: mariadb

- name: Create the databases
  mysql_db:
    name: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_databases }}"
  tags: mariadb

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_users }}"
  tags: mariadb

- name: Copy database init scripts
  copy:
    src: "{{ item.script }}"
    dest: "/tmp/{{ item.script|basename }}"
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb

- name: Initialise databases
  mysql_db:
    name: "{{ item.database }}"
    state: import
    target: "/tmp/{{ item.script|basename }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb
