# roles/mariadb/tasks/main.yml
---

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: mariadb_packages
  tags: mariadb

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
